name: Notify Telegram on Master Push

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="✅ *Yangi o'zgarishlar master branchga yuklandi!*\n\n"
          MESSAGE+="📌 Repository: [${{ github.repository }}](https://github.com/${{ github.repository }})\n"
          MESSAGE+="🔀 Branch: *${{ github.ref_name }}*\n"
          MESSAGE+="👤 Yuborgan: *${{ github.actor }}*\n"
          MESSAGE+="🔄 Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\n"

          # JSON formatiga o‘tkazish va yuborish
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d parse_mode="Markdown" \
            -d text="$(echo -e "$MESSAGE" | jq -Rs .)"
