name: Deploy to SFTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "./*"
          target: ${{ secrets.FTP_REMOTE_DIR }}

      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="🚀 *SFTP yuklandi!* ✅\n\n"
          MESSAGE+="📌 Repository: [${{ github.repository }}](https://github.com/${{ github.repository }})\n"
          MESSAGE+="🔀 Branch: *${{ github.ref_name }}*\n"
          MESSAGE+="👤 Yuklagan: *${{ github.actor }}*\n"
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d parse_mode="Markdown" \
            -d text="$(echo -e "$MESSAGE" | jq -Rs .)"
